### PR TITLE
fix(core): fixes for kmx_file rearrangement 🙀

### PR DESCRIPTION
**Pull request by srl295**
fix breaks in #7111 and prior

#7098

@keymanapp-test-bot skip

### CODE REVIEW

**Review by mcdurdin — APPROVED** [review]

File: common/include/km_types.h [hunk 1]
```diff
@@ -1,5 +1,7 @@
 #pragma once
 
+#include <stdint.h>
```
Comment (mcdurdin) [inline common/include/km_types.h:3]: Curious why this is needed?

Comment (srl295) [reply common/include/km_types.h:3]: @mcdurdin me too

Comment (srl295) [reply common/include/km_types.h:3]: i wonder if it used to be indirectly included somehow.  That's the danger of optimizing includes !

Comment (mcdurdin) [reply common/include/km_types.h:3]: So you found you needed it to build?

Comment (mcdurdin) [reply common/include/km_types.h:3]: Jenkins build is failing because of this line...

```
[2022-08-24T18:58:13.334Z] /<<PKGBUILDDIR>>/common/include/km_types.h:3:10: fatal error: cstdint: No such file or directory

[2022-08-24T18:58:13.334Z]  #include <cstdint>
```

Comment (srl295) [reply common/include/km_types.h:3]: for linux, yes.  I don't see a teamcity build that shows this, because it stopped on an earlier error. I can test that though

Comment (srl295) [reply common/include/km_types.h:3]: ^ @mcdurdin  that was old, i changed <cstdint> to <stdint.h> 

I opened https://github.com/keymanapp/keyman/pull/7117 to try skipping that line, to double check that it would fail on linux not just on srl-linux

Comment (srl295) [reply common/include/km_types.h:3]: i'll merge #7116 *unless* #7117  shows that the #include is unnecessary

Comment (srl295) [reply common/include/km_types.h:3]: ^ windows failed without that include… passed with.

**Comment by srl295** [comment]
jenkins failing, but it was already failing on  f5f1bfd … merging
