### ISSUE TITLE
bug(android): Error in Keyboard 'sil_euro..' for language message appears in Android 5.0 emulator 

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#7613]
### Describe the bug

After installing Keyman 16.0.95-beta build in API 21 / Android 5.0 emulator, there is an error message 'Error in Keyboard...' in the Keyman app. 

### Reproduce the bug

1. Install Keyman 16.0.94-beta build in Android 5.0 emulator. 
2. Open Keyman app. 
3. Here, I noticed that there is an error message appear 'Error in Keyboard...sil_euro_latin.. for langugae' at the bottom of the keyboard. 

I have attached the Screenshot for reference. 

   <img width="500" src="https://user-images.githubusercontent.com/19683143/199754905-42a626a8-aeba-4bbe-921e-d951059d7f20.png">

### Expected behavior

EuroLatin (SIL) keyboard should be installed successfully without showing any error message. 

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

16.0.94-beta 

### Operating system

Android 5.0 OS

### Device

API 21 Android Emulator

### Target application

Keyman app

### Keyboard name

EuroLatin (SIL) Keyboard

### Keyboard version

2.0

### Language name

English

**Comment by mcdurdin** [comment]
I think this is the error in question:

```
{
cm_lineNumber: 156, 
cm_message: Uncaught TypeError: undefined is not a function, 
cm_sourceID: blob:null/33618106-a159-46e3-8bf2-1678958ba1b9, 
keyboardID: sil_euro_latin, 
keyboardName: EuroLatin (SIL) Keyboard, 
keyboardType: INAPP, 
packageID: sil_euro_latin
}
```

https://sentry.io/organizations/keyman/issues/3468365898/events/f80dfd9603f24dc792674a8b551a29fe/

Which is a fault in the LMLayer worker code, but because it is minified, is really hard to figure out further.

**Comment by mcdurdin** [comment]
https://sentry.io/organizations/keyman/issues/3715854358/events/77dd5d1df6b7433aa8f8d30286cc6d87/ correlates closely

**Comment by darcywong00** [comment]
I did a bisect of the alpha releases and found for Android 5.0:
16.0.64 alpha - build runs fine with no error
16.0.67 alpha - build starts to show the error `Uncaught TypeError: undefined is not a function`

Possible model-related PR's in that release:
7274
#7279 (Maybe the spread syntax ([Chrome 46](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax)) is bombing on Android 5.0 (Chrome 37)
7313

**Comment by mcdurdin** [comment]
Minified code that is triggering the error appears to be in this block (`predict`):

https://github.com/keymanapp/keyman/blob/badf5e6d4b30e3bc5e4a55d6c5d82b11bf6aaab4/common/web/lm-worker/src/model-compositor.ts#L64-L141

**Comment by darcywong00** [comment]
Fixed in 16.0 beta by #7646
