### ISSUE TITLE
maint(common): move to meson 1.8.3

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#14198]
meson 1.8.3 will be released soon, which fixes a problem with xcode clang 17.0.0. Will be a hard error with next version of xcode (v26).

Ref:
* https://github.com/mesonbuild/meson/pull/14548
* Core builds failing on macOS with new version compilers

```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__config:48:6: error: "_LIBCPP_ENABLE_ASSERTIONS is deprecated, please use _LIBCPP_HARDENING_MODE instead" [-Werror,-W#warnings]
   48 | #    warning "_LIBCPP_ENABLE_ASSERTIONS is deprecated, please use _LIBCPP_HARDENING_MODE instead"
      |      ^
1 error generated.
ninja: build stopped: subcommand failed.
[core] ## build:mac-x86_64 failed
```

Fix will need to be backported to stable-18.0.

**Comment by ermshiperete** [comment]
We'll have to re-package that version and put on Launchpad for the currently released Ubuntu versions. If we could wait with raising the general requirement until 1.8(.3?) is available on Debian or Ubuntu this would probably be an easier task. Can we require 1.8.3 only on Mac for now?

**Comment by mcdurdin** [comment]
Sure, we can upgrade the mac agents to 1.8.3, and push this req to 20.0. I will work on the two mac agents.

**Comment by mcdurdin** [comment]
Currently, [latest version available on brew](https://formulae.brew.sh/formula/meson#default) is 1.8.2. Propose we wait until 1.8.3 is available on brew before upgrading, as we shouldn't need this on the build agents until then. For now, will postpone the whole issue until 20.0 unless we are forced into the xcode upgrade earlier.

**Comment by mcdurdin** [comment]
@sgschantz FYI

**Comment by mcdurdin** [comment]
Note, having trouble with meson 1.9.0 on Windows, results in a build failure for core:x86,x64:

```
plurrule.cpp.obj : error LNK2019: unresolved external symbol "public: virtual __thiscall icu_73::SharedPluralRules::~SharedPluralRules(void)" (??1SharedPluralRules@icu_73@@UAE@XZ) referenced in function "public: virtual void * __thiscall icu_73::SharedPluralRules::`vector deleting destructor'(unsigned int)" (??_ESharedPluralRules@icu_73@@UAEPAXI@Z)
```

msvc 2019, v16.11.51, but also msvc2022.

Have not yet investigated more deeply. Works with meson 1.5.1; have not bisected.
